-- ============================================================
-- Shanya store — Supabase setup for live product management
-- Run this ONCE in: Supabase Dashboard → SQL Editor → New query → Run
-- ============================================================

-- 1) Products table -----------------------------------------------------------
create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  title       text not null,
  price       numeric not null default 0,
  currency    text default '₹',
  description text,
  image       text,
  images      jsonb default '[]'::jsonb,
  stock       int default 0,
  category    text,
  created_at  timestamptz default now()
);

-- 2) Public can READ products; writes only via the service-role key (admin) ----
alter table public.products enable row level security;
drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select using (true);

-- 3) Seed the existing 6 products (keeps the same ids the storefront uses) ------
insert into public.products (id, title, price, currency, description, image, images, stock, category) values
(1,'Hooks',12,'₹','Durable adhesive and screw-in hooks for organizing coats, bags and kitchenware. Set of 10 with strong load capacity.','wall-hooks.avif','["wall-hooks.avif","wall-hooks-2.svg"]',91,'adhesive-hooks'),
(2,'Claw Clip',5,'₹','Stylish claw hair clip in a smooth resin finish — holds hair securely without damage. Available in multiple colors.','clow-clips.avif','["clow-clips.avif"]',15,'hair-accessories'),
(3,'Hair Extensions',79,'₹','Premium synthetic hair extensions for instant length and volume. Heat-resistant, easy to style and blend with natural hair.','hair-extansions.avif','["hair-extansions.avif"]',12,'hair-accessories'),
(4,'Knife Set',99,'₹','Professional 5-piece stainless steel kitchen knife set with ergonomic handles and a magnetic wooden block for safe storage.','knife-set.avif','["knife-set.avif"]',4,'kitchen-accessories'),
(5,'Key Ring',8,'₹','Leather key ring with a sturdy metal clasp — minimalist design to keep your keys organized and easy to carry.','key-ring.avif','["key-ring.avif"]',120,'key-chain'),
(6,'Decoration Kit',45,'₹','Curated home decoration kit including cushions, frames and small accents to refresh any room with a coordinated look.','decoration-kit.jpg','["decoration-kit.jpg"]',22,'birthday-decorations')
on conflict (id) do nothing;

-- keep auto-generated ids continuing AFTER the seeded ones
select setval(pg_get_serial_sequence('public.products','id'), (select max(id) from public.products));

-- 4) Storage bucket for admin image uploads (public read) ----------------------
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Allow public read of uploaded images
drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

-- Done. Now add SUPABASE_SERVICE_ROLE_KEY to your env (see DEPLOY.md).
